api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    
]

clients/urls.py
from django.urls import path

from clients import views

app_name = "clients"

urlpatterns = [
    
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('new/category/', views.NewCategory.as_view(), name="newcategory"),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name="update_category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name="detail_category"),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name="delete_category"),
]

providers/urls.py
from django.urls import path

from providers import views

app_name = "prov"

urlpatterns = [
    
]

sysplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('clients/', include("clients.urls")),
    path('providers/', include("providers.urls")),
    path('', include("home.urls")),
]

api/models.py
from django.db import models

# Create your models here.

clients/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=16, null=False, blank=False)
    bio = models.TextField(max_length=256, default="I Love This APP")
    timestamp = models.DateField(auto_now_add=True)
    age = models.IntegerField(default=18)
    weight = models.FloatField(default=50.45)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)



    def __str__(self):
        return self.name


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=32, default="Generic Category")
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name



class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=32, default="Generic Product")
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.product_name

providers/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms

from .models import Category

class UpdateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "user",
            "name",
            "status"
        ]


class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "user",
            "name",
            "status"
        ]

api/views.py
from django.shortcuts import render

# Create your views here.

clients/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from .models import Category
from .forms import UpdateCategoryForm, NewCategoryForm

class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request):
        self.context = {
            "categories": Category.objects.all()
        }
        return render(request, self.template_name, self.context)


class DetailCategory(generic.DetailView):
    template_name = "home/detail_category.html"
    model = Category


class UpdateCategory(generic.UpdateView):
    template_name = "home/update_category.html"
    model = Category
    form_class = UpdateCategoryForm
    success_url = reverse_lazy("home:index")



class DeleteCategory(generic.DeleteView):
    template_name = "home/delete_category.html"
    model = Category
    success_url = reverse_lazy("home:index")


class NewCategory(generic.CreateView):
    template_name = "home/newcategory.html"
    model = Category
    form_class = NewCategoryForm
    success_url = reverse_lazy("home:index")

providers/views.py
from django.shortcuts import render

# Create your views here.

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Class Project</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:newcategory' %}">New Category</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Actions
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
        {% block content %}
        {% endblock content %}
        <footer class="text-center text-white" style="background-color: #f1f1f1;">
          <!-- Grid container -->
          <div class="container pt-4">
            <!-- Section: Social media -->
            <section class="mb-4">
              <!-- Facebook -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="#!"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="fa-brands fa-facebook"></i></a>
        
              <!-- Twitter -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="#!"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="fab fa-twitter"></i
              ></a>
        
              <!-- Google -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="#!"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="fab fa-google"></i
              ></a>
        
              <!-- Instagram -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="#!"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="fab fa-instagram"></i
              ></a>
        
              <!-- Linkedin -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="#!"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="fab fa-linkedin"></i
              ></a>
              <!-- Github -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="#!"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="fab fa-github"></i
              ></a>
            </section>
            <!-- Section: Social media -->
          </div>
          <!-- Grid container -->
        
          <!-- Copyright -->
          <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
          </div>
          <!-- Copyright -->
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.js' %}" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

templates/home/about.html
<h1>Soy el About, Nice To Meet You!</h1>

templates/home/delete_category.html
{% extends 'base/base.html' %}

{% block title %}Delete Category View {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            ¿ Realmente deseas eliminar esta categoria: <strong>{{object}}??</strong>
            <a href="{% url 'home:index' %}" class="btn btn-outline-info">Cancel</a>
            <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

templates/home/detail_category.html
{% extends 'base/base.html' %}

{% block title %}Detail Category View{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the category created by: <strong> {{ object.user }}</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code> This category has a status:  </code> {{ object.status }}, though the transition does a timestamp.
            <small><a href="{% url 'home:index' %}" class="btn btn-link">back to home</a></small> 
        </div>
      </div>
    </div>
    
    
    
{% endblock content %}

templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}Index View{% endblock title %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>STATUS</th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for category in categories %}
                <tr>
                    <td>{{ category.id }}</td>
                    <td>{{ category.name }}</td>
                    <td>{{ category.status }}</td>
                    <td><a href="{% url 'home:detail_category' category.id %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'home:update_category' category.id %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'home:delete_category' category.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/home/newcategory.html
{% extends 'base/base.html' %}

{% block title %}New Category View {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:index'%}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">New Category</button>
    </form>
{% endblock content %}

templates/home/update_category.html
{% extends 'base/base.html' %}

{% block title %}Update Category View {% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:index'%}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-warning">Update</button>
    </form>
{% endblock content %}